### ISSUE TITLE
Error  plugins from bukkit

### ISSUE THREAD

**Issue by comdarksider** [Maxqia/PoreRT#2] opened 2016-09-29 10:22 UTC
Error in spongeforge-1.10.2-API5.0-2092-1758
Worldguard from bukkit not working normal.

link error message : http://pastebin.com/nKF3g4Z73

**Comment by mbax** [comment] 2016-10-03 03:35
@comdarksider the paste is gone ;)

**Comment by Maxqia** [comment] 2016-10-03 04:31
It has an extra 3 at the end ...

**Comment by Maxqia** [comment] 2016-12-25 18:49
Dupe of #13

**Closed as completed by Maxqia** 2016-12-25 18:49 UTC
